packages:
  - "minminimal-react-app"
  # include packages in subfolders (e.g., webview-ui)
  - 'webview-ui'
  # include root package.json
  - '.'

# Optional: Keep existing ignored dependencies if needed
ignoredBuiltDependencies:
  - esbuild
